name: urban_backscatter
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - netcdf4
  - xarray
  - rioxarray
  - seaborn
  - jupyterlab
  - pandas
  - python=3.9
  - pytest
  - pre-commit
  - flake8
  - black
  - pytest-cov
